### ISSUE TITLE
NonLinearPlaceFPGA.dump() not defined

### ISSUE THREAD

**Issue by hailiangh** [rachelselinar/DREAMPlaceFPGA#22]
The issue is in file `dreamplacefpga/NonLinearPlace.py`, line 712.
The function `self.dump()` is not defined. 

To reproduce the error:

Add the following option in `test/FPGA-example1.json`:
```
"dump_global_place_solution_flag" : 1
```

Then run the following command:
```
python dreamplacefpga/Placer.py test/FPGA-example1.json
```

Error message:
```
Traceback (most recent call last):
  File "dreamplacefpga/Placer.py", line 120, in <module>
    placeFPGA(params)
  File "dreamplacefpga/Placer.py", line 44, in placeFPGA
    metrics = placer(params, placedb)
  File "/home/grads/h/hailiang/DREAMPlaceFPGA/dreamplacefpga/NonLinearPlace.py", line 712, in __call__
    self.dump(params, placedb, self.pos[0].cpu(), "%s.lg.pklz" %(params.design_name()))
  File "/home/grads/h/hailiang/anaconda3/envs/dreamplacefpga/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'NonLinearPlaceFPGA' object has no attribute 'dump'
```

Possible method to fix this issue:
Add the `dump()` and `load()` function in `dreamplacefpga/BasicPlace.py` as in DREAMPlace.  (I think dump and load work in pairs.)
Links to example: [dump( )](https://github.com/limbo018/DREAMPlace/blob/f59ebfa4831573d3db38642f4b2d2e2108bd6e3e/dreamplace/BasicPlace.py#L1102), [load( )](https://github.com/limbo018/DREAMPlace/blob/f59ebfa4831573d3db38642f4b2d2e2108bd6e3e/dreamplace/BasicPlace.py#L1129).

**Comment by rachelselinar** [comment]
Created initial versions for dump() and load() functions in branch 'load_dump_feature'
Will verify use case before merging.
